FROM golang:1.17-alpine  AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o server .

FROM scratch

COPY --from=builder /app/server /server
 
EXPOSE 8080
ENTRYPOINT ["/server"]
